### ISSUE TITLE
'Access-Control-Allow-Origin' error

### ISSUE THREAD

**Issue by erikmohn** [TobbenTM/MMM-OsloCityBike#1]
Got issues with 'Access-Control-Allow-Origin' errors with this module.

Fixed temporary here with disabling security:    /MagicMirror/js/electron.js ->

 webPreferences: {
                        webSecurity: false
                }

**Comment by TobbenTM** [comment]
Thanks for the report and for sharing your temporary fix.

Unfortunately my MIrror is not operational at the moment, so it might be a while till I get the chance to take a look at this.

A quick look at the Ruter API suggests they are infact not including any CORS related headers, so we're either going to have to move the API interaction server-side, or submit a feature request to Ruter. The former seems most probable.

**Comment by igundersen** [comment]
I have submitted a pull request to fix this. All I had to do was to add http**s**

**Comment by TobbenTM** [comment]
Closing since @igundersen submitted a lovely PR, let me know if this still happens! :)
